-- Seed challenges table with geographic challenges

-- Easy challenges
INSERT INTO challenges (id, location_name, latitude, longitude, country, continent, difficulty, max_distance_km) VALUES
    ('new_york_united_states', 'New York', 40.7128, -74.0060, 'United States', 'North America', 'easy', 10000),
    ('london_united_kingdom', 'London', 51.5074, -0.1278, 'United Kingdom', 'Europe', 'easy', 10000),
    ('paris_france', 'Paris', 48.8566, 2.3522, 'France', 'Europe', 'easy', 10000),
    ('tokyo_japan', 'Tokyo', 35.6762, 139.6503, 'Japan', 'Asia', 'easy', 10000),
    ('sydney_australia', 'Sydney', -33.8688, 151.2093, 'Australia', 'Oceania', 'easy', 10000),
    ('berlin_germany', 'Berlin', 52.5200, 13.4050, 'Germany', 'Europe', 'easy', 10000),
    ('rome_italy', 'Rome', 41.9028, 12.4964, 'Italy', 'Europe', 'easy', 10000),
    ('madrid_spain', 'Madrid', 40.4168, -3.7038, 'Spain', 'Europe', 'easy', 10000),
    ('moscow_russia', 'Moscow', 55.7558, 37.6176, 'Russia', 'Europe', 'easy', 10000),
    ('beijing_china', 'Beijing', 39.9042, 116.4074, 'China', 'Asia', 'easy', 10000),
    ('los_angeles_united_states', 'Los Angeles', 34.0522, -118.2437, 'United States', 'North America', 'easy', 10000),
    ('chicago_united_states', 'Chicago', 41.8781, -87.6298, 'United States', 'North America', 'easy', 10000),
    ('toronto_canada', 'Toronto', 43.6532, -79.3832, 'Canada', 'North America', 'easy', 10000),
    ('mexico_city_mexico', 'Mexico City', 19.4326, -99.1332, 'Mexico', 'North America', 'easy', 10000),
    ('sao_paulo_brazil', 'São Paulo', -23.5505, -46.6333, 'Brazil', 'South America', 'easy', 10000),
    ('buenos_aires_argentina', 'Buenos Aires', -34.6118, -58.3960, 'Argentina', 'South America', 'easy', 10000),
    ('cairo_egypt', 'Cairo', 30.0444, 31.2357, 'Egypt', 'Africa', 'easy', 10000),
    ('mumbai_india', 'Mumbai', 19.0760, 72.8777, 'India', 'Asia', 'easy', 10000),
    ('dubai_uae', 'Dubai', 25.2048, 55.2708, 'UAE', 'Asia', 'easy', 10000),
    ('singapore_singapore', 'Singapore', 1.3521, 103.8198, 'Singapore', 'Asia', 'easy', 10000)
ON CONFLICT (id) DO UPDATE SET
    location_name = EXCLUDED.location_name,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    country = EXCLUDED.country,
    continent = EXCLUDED.continent,
    difficulty = EXCLUDED.difficulty,
    max_distance_km = EXCLUDED.max_distance_km;

-- Medium challenges
INSERT INTO challenges (id, location_name, latitude, longitude, country, continent, difficulty, max_distance_km) VALUES
    ('rio_de_janeiro_brazil', 'Rio de Janeiro', -22.9068, -43.1729, 'Brazil', 'South America', 'medium', 5000),
    ('istanbul_turkey', 'Istanbul', 41.0082, 28.9784, 'Turkey', 'Europe', 'medium', 5000),
    ('cape_town_south_africa', 'Cape Town', -33.9249, 18.4241, 'South Africa', 'Africa', 'medium', 5000),
    ('barcelona_spain', 'Barcelona', 41.3851, 2.1734, 'Spain', 'Europe', 'medium', 5000),
    ('amsterdam_netherlands', 'Amsterdam', 52.3676, 4.9041, 'Netherlands', 'Europe', 'medium', 5000),
    ('vienna_austria', 'Vienna', 48.2082, 16.3738, 'Austria', 'Europe', 'medium', 5000),
    ('prague_czech_republic', 'Prague', 50.0755, 14.4378, 'Czech Republic', 'Europe', 'medium', 5000),
    ('budapest_hungary', 'Budapest', 47.4979, 19.0402, 'Hungary', 'Europe', 'medium', 5000),
    ('stockholm_sweden', 'Stockholm', 59.3293, 18.0686, 'Sweden', 'Europe', 'medium', 5000),
    ('dublin_ireland', 'Dublin', 53.3498, -6.2603, 'Ireland', 'Europe', 'medium', 5000),
    ('lisbon_portugal', 'Lisbon', 38.7223, -9.1393, 'Portugal', 'Europe', 'medium', 5000),
    ('athens_greece', 'Athens', 37.9838, 23.7275, 'Greece', 'Europe', 'medium', 5000),
    ('seoul_south_korea', 'Seoul', 37.5665, 126.9780, 'South Korea', 'Asia', 'medium', 5000),
    ('bangkok_thailand', 'Bangkok', 13.7563, 100.5018, 'Thailand', 'Asia', 'medium', 5000),
    ('nairobi_kenya', 'Nairobi', 1.2921, 36.8219, 'Kenya', 'Africa', 'medium', 5000)
ON CONFLICT (id) DO UPDATE SET
    location_name = EXCLUDED.location_name,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    country = EXCLUDED.country,
    continent = EXCLUDED.continent,
    difficulty = EXCLUDED.difficulty,
    max_distance_km = EXCLUDED.max_distance_km;

-- Hard challenges
INSERT INTO challenges (id, location_name, latitude, longitude, country, continent, difficulty, max_distance_km) VALUES
    ('ulaanbaatar_mongolia', 'Ulaanbaatar', 47.8864, 106.9057, 'Mongolia', 'Asia', 'hard', 2500),
    ('reykjavik_iceland', 'Reykjavik', 64.1466, -21.9426, 'Iceland', 'Europe', 'hard', 2500),
    ('antananarivo_madagascar', 'Antananarivo', -18.8792, 47.5079, 'Madagascar', 'Africa', 'hard', 2500),
    ('tbilisi_georgia', 'Tbilisi', 41.7151, 44.8271, 'Georgia', 'Asia', 'hard', 2500),
    ('riga_latvia', 'Riga', 56.9496, 24.1052, 'Latvia', 'Europe', 'hard', 2500),
    ('tallinn_estonia', 'Tallinn', 59.4370, 24.7536, 'Estonia', 'Europe', 'hard', 2500),
    ('ljubljana_slovenia', 'Ljubljana', 46.0569, 14.5058, 'Slovenia', 'Europe', 'hard', 2500),
    ('zagreb_croatia', 'Zagreb', 45.8150, 15.9819, 'Croatia', 'Europe', 'hard', 2500),
    ('sarajevo_bosnia', 'Sarajevo', 43.8486, 18.3564, 'Bosnia', 'Europe', 'hard', 2500),
    ('windhoek_namibia', 'Windhoek', -22.5597, 17.0832, 'Namibia', 'Africa', 'hard', 2500)
ON CONFLICT (id) DO UPDATE SET
    location_name = EXCLUDED.location_name,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    country = EXCLUDED.country,
    continent = EXCLUDED.continent,
    difficulty = EXCLUDED.difficulty,
    max_distance_km = EXCLUDED.max_distance_km;

-- Expert challenges
INSERT INTO challenges (id, location_name, latitude, longitude, country, continent, difficulty, max_distance_km) VALUES
    ('nuuk_greenland', 'Nuuk', 64.1836, -51.7214, 'Greenland', 'North America', 'expert', 1000),
    ('funafuti_tuvalu', 'Funafuti', -8.5167, 179.2167, 'Tuvalu', 'Oceania', 'expert', 1000),
    ('thimphu_bhutan', 'Thimphu', 27.4728, 89.6390, 'Bhutan', 'Asia', 'expert', 1000),
    ('male_maldives', 'Malé', 4.1755, 73.5093, 'Maldives', 'Asia', 'expert', 1000),
    ('port_vila_vanuatu', 'Port Vila', -17.7333, 168.3273, 'Vanuatu', 'Oceania', 'expert', 1000),
    ('dili_east_timor', 'Dili', -8.5569, 125.5603, 'East Timor', 'Asia', 'expert', 1000),
    ('praia_cape_verde', 'Praia', 14.9177, -23.5092, 'Cape Verde', 'Africa', 'expert', 1000),
    ('victoria_seychelles', 'Victoria', -4.6199, 55.4513, 'Seychelles', 'Africa', 'expert', 1000),
    ('moroni_comoros', 'Moroni', -11.7172, 43.2473, 'Comoros', 'Africa', 'expert', 1000),
    ('banjul_gambia', 'Banjul', 13.4549, -16.5790, 'Gambia', 'Africa', 'expert', 1000)
ON CONFLICT (id) DO UPDATE SET
    location_name = EXCLUDED.location_name,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    country = EXCLUDED.country,
    continent = EXCLUDED.continent,
    difficulty = EXCLUDED.difficulty,
    max_distance_km = EXCLUDED.max_distance_km;

-- Seed hints for challenges
-- Easy challenges hints
INSERT INTO challenge_hints (challenge_id, hint_text, hint_order) VALUES
    ('new_york_united_states', 'Largest city in USA', 1),
    ('new_york_united_states', 'Big Apple', 2),
    ('new_york_united_states', 'Statue of Liberty', 3),
    ('london_united_kingdom', 'Big Ben', 1),
    ('london_united_kingdom', 'Thames River', 2),
    ('london_united_kingdom', 'Capital of UK', 3),
    ('paris_france', 'Eiffel Tower', 1),
    ('paris_france', 'City of Light', 2),
    ('paris_france', 'Capital of France', 3),
    ('tokyo_japan', 'Capital of Japan', 1),
    ('tokyo_japan', 'Mount Fuji nearby', 2),
    ('tokyo_japan', 'Largest metro area', 3),
    ('sydney_australia', 'Opera House', 1),
    ('sydney_australia', 'Harbor Bridge', 2),
    ('sydney_australia', 'Largest city in Australia', 3),
    ('berlin_germany', 'Brandenburg Gate', 1),
    ('berlin_germany', 'Capital of Germany', 2),
    ('berlin_germany', 'Berlin Wall', 3),
    ('rome_italy', 'Colosseum', 1),
    ('rome_italy', 'Vatican', 2),
    ('rome_italy', 'Eternal City', 3),
    ('madrid_spain', 'Prado Museum', 1),
    ('madrid_spain', 'Capital of Spain', 2),
    ('madrid_spain', 'Royal Palace', 3),
    ('moscow_russia', 'Red Square', 1),
    ('moscow_russia', 'Kremlin', 2),
    ('moscow_russia', 'Capital of Russia', 3),
    ('beijing_china', 'Forbidden City', 1),
    ('beijing_china', 'Great Wall nearby', 2),
    ('beijing_china', 'Capital of China', 3),
    ('los_angeles_united_states', 'Hollywood', 1),
    ('los_angeles_united_states', 'Beverly Hills', 2),
    ('los_angeles_united_states', 'City of Angels', 3),
    ('chicago_united_states', 'Windy City', 1),
    ('chicago_united_states', 'Sears Tower', 2),
    ('chicago_united_states', 'Great Lakes', 3),
    ('toronto_canada', 'CN Tower', 1),
    ('toronto_canada', 'Largest city in Canada', 2),
    ('toronto_canada', 'Great Lakes', 3),
    ('mexico_city_mexico', 'Largest city in Mexico', 1),
    ('mexico_city_mexico', 'Aztec heritage', 2),
    ('mexico_city_mexico', 'High altitude', 3),
    ('sao_paulo_brazil', 'Largest city in Brazil', 1),
    ('sao_paulo_brazil', 'Economic center', 2),
    ('sao_paulo_brazil', 'South America', 3),
    ('buenos_aires_argentina', 'Tango', 1),
    ('buenos_aires_argentina', 'Capital of Argentina', 2),
    ('buenos_aires_argentina', 'Paris of South America', 3),
    ('cairo_egypt', 'Pyramids nearby', 1),
    ('cairo_egypt', 'Nile River', 2),
    ('cairo_egypt', 'Capital of Egypt', 3),
    ('mumbai_india', 'Bollywood', 1),
    ('mumbai_india', 'Gateway of India', 2),
    ('mumbai_india', 'Financial capital', 3),
    ('dubai_uae', 'Burj Khalifa', 1),
    ('dubai_uae', 'Desert city', 2),
    ('dubai_uae', 'Modern architecture', 3),
    ('singapore_singapore', 'City-state', 1),
    ('singapore_singapore', 'Marina Bay', 2),
    ('singapore_singapore', 'Garden City', 3)
ON CONFLICT DO NOTHING;

-- Medium challenges hints
INSERT INTO challenge_hints (challenge_id, hint_text, hint_order) VALUES
    ('rio_de_janeiro_brazil', 'Christ the Redeemer', 1),
    ('rio_de_janeiro_brazil', 'Copacabana Beach', 2),
    ('rio_de_janeiro_brazil', 'Former capital', 3),
    ('istanbul_turkey', 'Bosphorus Bridge', 1),
    ('istanbul_turkey', 'Between two continents', 2),
    ('istanbul_turkey', 'Former Constantinople', 3),
    ('cape_town_south_africa', 'Table Mountain', 1),
    ('cape_town_south_africa', 'Cape of Good Hope', 2),
    ('cape_town_south_africa', 'Legislative capital', 3),
    ('barcelona_spain', 'Sagrada Familia', 1),
    ('barcelona_spain', 'Mediterranean coast', 2),
    ('barcelona_spain', 'Gaudi architecture', 3),
    ('amsterdam_netherlands', 'Canals', 1),
    ('amsterdam_netherlands', 'Tulips', 2),
    ('amsterdam_netherlands', 'Capital of Netherlands', 3),
    ('vienna_austria', 'Classical music', 1),
    ('vienna_austria', 'Danube River', 2),
    ('vienna_austria', 'Imperial palaces', 3),
    ('prague_czech_republic', 'Charles Bridge', 1),
    ('prague_czech_republic', 'Golden City', 2),
    ('prague_czech_republic', 'Medieval architecture', 3),
    ('budapest_hungary', 'Danube River', 1),
    ('budapest_hungary', 'Thermal baths', 2),
    ('budapest_hungary', 'Parliament building', 3),
    ('stockholm_sweden', 'Capital of Sweden', 1),
    ('stockholm_sweden', '14 islands', 2),
    ('stockholm_sweden', 'Nobel Prize', 3),
    ('dublin_ireland', 'Trinity College', 1),
    ('dublin_ireland', 'Guinness', 2),
    ('dublin_ireland', 'Emerald Isle', 3),
    ('lisbon_portugal', 'Atlantic coast', 1),
    ('lisbon_portugal', 'Age of exploration', 2),
    ('lisbon_portugal', 'Fado music', 3),
    ('athens_greece', 'Acropolis', 1),
    ('athens_greece', 'Parthenon', 2),
    ('athens_greece', 'Birthplace of democracy', 3),
    ('seoul_south_korea', 'K-pop', 1),
    ('seoul_south_korea', 'Technology hub', 2),
    ('seoul_south_korea', 'Korean culture', 3),
    ('bangkok_thailand', 'Capital of Thailand', 1),
    ('bangkok_thailand', 'Buddhist temples', 2),
    ('bangkok_thailand', 'Street food', 3),
    ('nairobi_kenya', 'Capital of Kenya', 1),
    ('nairobi_kenya', 'Safari hub', 2),
    ('nairobi_kenya', 'Great Rift Valley', 3)
ON CONFLICT DO NOTHING;

-- Hard challenges hints
INSERT INTO challenge_hints (challenge_id, hint_text, hint_order) VALUES
    ('ulaanbaatar_mongolia', 'Capital of Mongolia', 1),
    ('ulaanbaatar_mongolia', 'Coldest capital', 2),
    ('ulaanbaatar_mongolia', 'Genghis Khan', 3),
    ('reykjavik_iceland', 'Northernmost capital', 1),
    ('reykjavik_iceland', 'Geysers', 2),
    ('reykjavik_iceland', 'Northern Lights', 3),
    ('antananarivo_madagascar', 'Capital of Madagascar', 1),
    ('antananarivo_madagascar', 'Island nation', 2),
    ('antananarivo_madagascar', 'Lemurs', 3),
    ('tbilisi_georgia', 'Capital of Georgia', 1),
    ('tbilisi_georgia', 'Caucasus mountains', 2),
    ('tbilisi_georgia', 'Wine country', 3),
    ('riga_latvia', 'Capital of Latvia', 1),
    ('riga_latvia', 'Art nouveau', 2),
    ('riga_latvia', 'Baltic Sea', 3),
    ('tallinn_estonia', 'Capital of Estonia', 1),
    ('tallinn_estonia', 'Digital nomads', 2),
    ('tallinn_estonia', 'Medieval walls', 3),
    ('ljubljana_slovenia', 'Capital of Slovenia', 1),
    ('ljubljana_slovenia', 'Lake Bled nearby', 2),
    ('ljubljana_slovenia', 'Green capital', 3),
    ('zagreb_croatia', 'Capital of Croatia', 1),
    ('zagreb_croatia', 'Adriatic Sea nearby', 2),
    ('zagreb_croatia', 'Balkan country', 3),
    ('sarajevo_bosnia', 'Capital of Bosnia', 1),
    ('sarajevo_bosnia', '1984 Olympics', 2),
    ('sarajevo_bosnia', 'Siege history', 3),
    ('windhoek_namibia', 'Capital of Namibia', 1),
    ('windhoek_namibia', 'Kalahari Desert', 2),
    ('windhoek_namibia', 'German colonial', 3)
ON CONFLICT DO NOTHING;

-- Expert challenges hints
INSERT INTO challenge_hints (challenge_id, hint_text, hint_order) VALUES
    ('nuuk_greenland', 'Capital of Greenland', 1),
    ('nuuk_greenland', 'Arctic Circle', 2),
    ('nuuk_greenland', 'Icebergs', 3),
    ('funafuti_tuvalu', 'Capital of Tuvalu', 1),
    ('funafuti_tuvalu', 'Smallest country', 2),
    ('funafuti_tuvalu', 'Rising sea levels', 3),
    ('thimphu_bhutan', 'Capital of Bhutan', 1),
    ('thimphu_bhutan', 'Happiness index', 2),
    ('thimphu_bhutan', 'Buddhist kingdom', 3),
    ('male_maldives', 'Capital of Maldives', 1),
    ('male_maldives', 'Lowest country', 2),
    ('male_maldives', 'Coral atolls', 3),
    ('port_vila_vanuatu', 'Capital of Vanuatu', 1),
    ('port_vila_vanuatu', 'Pacific islands', 2),
    ('port_vila_vanuatu', 'Volcanoes', 3),
    ('dili_east_timor', 'Capital of East Timor', 1),
    ('dili_east_timor', 'Newest Asian nation', 2),
    ('dili_east_timor', 'Portuguese colonial', 3),
    ('praia_cape_verde', 'Capital of Cape Verde', 1),
    ('praia_cape_verde', 'Atlantic islands', 2),
    ('praia_cape_verde', 'Creole culture', 3),
    ('victoria_seychelles', 'Capital of Seychelles', 1),
    ('victoria_seychelles', 'Granite islands', 2),
    ('victoria_seychelles', 'Indian Ocean', 3),
    ('moroni_comoros', 'Capital of Comoros', 1),
    ('moroni_comoros', 'Volcanic islands', 2),
    ('moroni_comoros', 'Ylang-ylang perfume', 3),
    ('banjul_gambia', 'Capital of Gambia', 1),
    ('banjul_gambia', 'Smallest African mainland country', 2),
    ('banjul_gambia', 'River Gambia', 3)
ON CONFLICT DO NOTHING;
